// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TallerAPI.Models;

namespace TallerAPI.Migrations
{
    [DbContext(typeof(ContactoAPIContext))]
    partial class ContactoAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TallerAPI.Models.ContactoAPI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApellidosContratoAPI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CelularContratoAPI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailContratoAPI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombresContratoAPI")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactoAPIs");
                });
#pragma warning restore 612, 618
        }
    }
}
